tasks:
  - name: Install tfenv
    init: brew install tfenv
    command: gp sync-done tfenv
  - name: Install tflint
    command: brew install tflint
  - name: Install Terraform
    command: |
      gp await-sync tfenv && \
      cd $GITPOD_REPO_ROOT/terraform && \
      tfenv install min-required && \
      tfenv use min-required && \
      cd $GITPOD_REPO_ROOT

vscode:
  extensions:
    - TabNine.tabnine-vscode
    - hashicorp.terraform
