image:
  file: .gitpod.Dockerfile
tasks:
  - name: Install Terraform
    command: |
      gp sync-await tfenv && \
      cd $GITPOD_REPO_ROOT/terraform && \
      tfenv install min-required && \
      tfenv use min-required && \
      cd $GITPOD_REPO_ROOT && \ 
      gp sync-done tfinstall
  - name: Init Terraform and TFlint
    command: |
      gp sync-await tfinstall && \
      cd $GITPOD_REPO_ROOT/terraform && \
      terraform init && \
      tflint --init && \
      cd $GITPOD_REPO_ROOT


vscode:
  extensions:
    - TabNine.tabnine-vscode
    - hashicorp.terraform

github:
  prebuilds:
    master: true
    pullRequests: true
    addComment: true